<a href="https://colab.research.google.com/github/mehmetaliisik/TensorFlow/blob/main/TensorFlow_Notes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.17.0


In [ ]:
# Create tensor with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2 = tf.constant([[10., 7.],
                       [3., 5.],
                       [8., 2.]], dtype = tf.float16) # Specify the data type with dtype parameter
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.],
       [ 8.,  2.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                      [3,4,5]],
                      [[1,2,3],
                      [3,4,5]],
                      [[1,2,3],
                      [3,4,5]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2 dimensional array of numbers
* Tensor: a n-dimensional array of numbers

### Creating tensors with `tf.variable`

In [ ]:
# Create same tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchengeable_tensor = tf.constant([10, 7])
changeable_tensor, unchengeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Chane one of the the elements in changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

> 🔑 **Note:** With the `tf.constant()` tensor will be unchangeable bu if you want to change use `tf.Variable()` function

### Random Tensors

In [ ]:
# Create random tensor
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape = (3, 2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3, 2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of tensor elements

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[2, 5],
                            [8, 10],
                            [1, 6]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 1,  6],
       [ 8, 10]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed = 42) # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 8, 10],
       [ 1,  6]], dtype=int32)>

`tf.random.set_seed(42` sets the global seed, and the seed parameter in `tf.random.shuffle(seed=42)` sets the operation seed.
Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."
> "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Other ways to make sensors

In [ ]:
# Create a sensor with all ones
tf.ones([3,5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a senzor with all zeros
tf.zeros(shape = (2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensor is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np

"""
X = tf.constant(some_matrix) # capital for matrix or tensor
y = tf.constant(vector) # non-capital for vector
"""
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape = [2, 3, 4])
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [1,2,3,4])
rank_4_tensor

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("Shape of tensor: ",rank_4_tensor.shape)
print("Number of dimensions of tensor (rank): ", rank_4_tensor.ndim)
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Shape of tensor:  (1, 2, 3, 4)
Number of dimensions of tensor (rank):  4
Total number of elements in our tensor:  tf.Tensor(24, shape=(), dtype=int32)
Total number of elements in our tensor:  24


### Indexing Tensors

Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 6]])
rank_2_tensor.ndim

2

In [ ]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 6]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 6]]], dtype=int32)>

### Manipulating Tensors (Tensor Operations)
**Basic Operations:**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using addition operator
tensor = tf.constant([[10, 7],
                      [5, 3]])
tensor + 10, tensor*10, tensor - 10, tensor/10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [15, 13]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 50,  30]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-5, -7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.5, 0.3]])>)

In [ ]:
# Also can compute with tf.multiply function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 50,  30]], dtype=int32)>

**Matrix Multiplication**

In ML, matrix multiplication is one of the most common tensor operations

In [ ]:
# MAtrix multiplication in tensorflow "matmul()"
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135,  91],
       [ 65,  44]], dtype=int32)>

In [ ]:
tensor1 = tf.constant([[1, 2, 5],
                       [7, 2, 1],
                       [3, 3, 3]])
tensor2 = tf.constant([[3, 5],
                       [6, 7],
                       [1, 8]])
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator "@"
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Reshape the tensor
tf.reshape(tensor2, shape = (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [ ]:
tf.transpose(tensor2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [ ]:
tensor1, tensor2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
# Perform dot product with tf.tensordot()
tf.tensordot(tensor1, tensor2, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

**Dot Production:**

* `tf.matmul()`
* `tf.tensordot()`
* `@`

### Changing DataType of a Tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.5, 4.7])
B.dtype

tf.float32

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 4.7], dtype=float16)>

### Aggregating Tensors

**Aggregating Tensors:** Condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
C = tf.constant([-4, -8])
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with the values between 0 to 100 of size 50
D = tf.constant(np.random.randint(0, 100, size = 50))
D

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([65, 44, 84, 43, 14, 36, 12, 52, 72,  5, 39, 35, 13, 81, 65, 58, 74,
       42, 43, 27,  2, 43, 79, 95, 28, 91,  5, 37, 81, 71, 97, 81, 28,  2,
       23, 90, 14, 18, 22, 27,  4, 96, 98, 99, 50, 46, 62,  5, 41, 23])>

In [ ]:
# Find the minimum
tf.reduce_min(D).numpy()

0

In [ ]:
# Find the maximum
tf.reduce_max(D).numpy()

98

In [ ]:
# Find the mean
tf.reduce_mean(D).numpy()

53

In [ ]:
# Find the sum
tf.reduce_sum(D).numpy()

2667

In [ ]:
# Find the variance
tf.math.reduce_variance(tf.cast(D, tf.float32)).numpy()

910.9824

In [ ]:
# Find the standart deviation
tf.math.reduce_std(tf.cast(D, tf.float32)).numpy()

30.182486

### Find the positional minimum and maximum

In [ ]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
E = tf.random.uniform(shape = [50])
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(E).numpy()

42

In [ ]:
# Index our largest value position
E[tf.argmax(E)].numpy(), tf.reduce_max(E).numpy()

(0.9671384, 0.9671384)

In [ ]:
# Find the positional minimum
tf.argmin(E).numpy()

16

In [ ]:
# Index our smallest value position
E[16].numpy(), tf.reduce_min(E).numpy()

(0.009463668, 0.009463668)

### Sqeezing a Tensor (Removing all single dimensions)

In [ ]:
# Create a tensor
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape = [50]), shape =[1, 1, 1, 1, 50])
F

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
F_squeezed = tf.squeeze(F)
F_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-Hot Encoding Tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be green, red, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth = 4, on_value = "Big", off_value = "Small")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Big', b'Small', b'Small', b'Small'],
       [b'Small', b'Big', b'Small', b'Small'],
       [b'Small', b'Small', b'Big', b'Small'],
       [b'Small', b'Small', b'Small', b'Big']], dtype=object)>

### Squaring, log, Square root

In [ ]:
G = tf.range(1, 10)
G

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square the tensor G
tf.square(G)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
tf.sqrt(tf.cast(G, dtype = tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# Find the log
tf.math.log(tf.cast(G, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy
TensorFlow interacts beautifuly with NumPy arrays

In [ ]:
# Create a tensor directly from a NumPy array
H = tf.constant(np.array([1., 5., 10.]))
H

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  5., 10.])>

In [ ]:
# Convert the tensor back to NumPy array
np.array(H), type(np.array(H))

(array([ 1.,  5., 10.]), numpy.ndarray)